-- MEMBER 테이블의 NAME 컬럼 크기 확장
-- 현재: VARCHAR2(10) -> 변경: VARCHAR2(50)

-- 방법 1: ALTER TABLE로 컬럼 크기 변경 (권장)
ALTER TABLE MEMBER MODIFY NAME VARCHAR2(50);

-- 방법 2: 테이블이 비어있다면 DROP 후 재생성
-- DROP TABLE MEMBER;
-- CREATE TABLE MEMBER (
--     NAME VARCHAR2(50),
--     USERID VARCHAR2(20),
--     PWD VARCHAR2(20),
--     EMAIL VARCHAR2(50),
--     PHONE VARCHAR2(20),
--     ADMIN NUMBER(1)
-- );

-- 변경 확인
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'MEMBER' 
ORDER BY COLUMN_ID;

